/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/layout/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    HomeQuickActions: typeof import('./src/components/home/HomeQuickActions.vue')['default']
    HostEditorDialog: typeof import('./src/components/host/HostEditorDialog.vue')['default']
    HostList: typeof import('./src/components/host/HostList.vue')['default']
    ServerStatusPanel: typeof import('./src/components/status/ServerStatusPanel.vue')['default']
    TerminalPane: typeof import('./src/components/terminal/TerminalPane.vue')['default']
    TerminalTabs: typeof import('./src/components/terminal/TerminalTabs.vue')['default']
    XtermView: typeof import('./src/components/terminal/XtermView.vue')['default']
  }
}
